[project]
name = "flights"
version = "0.0.1"
authors = [{"name" = "Andres Garcia"}]
description = "Demo DABS Project"

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
package-dir = {"flights" = "./src/flights"}